# Generated by Django 5.2.1 on 2025-05-13 06:45

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        ('vocabs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gedenkzeichen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name des Gedenkzeichens', max_length=250)),
                ('start_date', models.DateField(blank=True, help_text='The day the Gedenkzeichen started', null=True, verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, help_text='The day the Gedenkzeichen ended', null=True, verbose_name='End date')),
                ('date_accuracy_start', models.CharField(blank=True, choices=[('Y', 'Year'), ('YM', 'Month'), ('DMY', 'Day')], default='Y', help_text='An information stating whether the given start date is accurate', max_length=3, null=True, verbose_name='Date accuracy start date')),
                ('date_accuracy_end', models.CharField(blank=True, choices=[('Y', 'Year'), ('YM', 'Month'), ('DMY', 'Day')], default='Y', help_text='An information stating whether the given end date is accurate', max_length=3, null=True, verbose_name='Date accuracy end date')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Description', null=True, verbose_name='Description')),
                ('legacy_id', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, help_text='The location of the Gedenkzeichen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_of_gedenkzeichen', to='entities.place')),
                ('object_type', models.ForeignKey(blank=True, help_text='The Gedenkzeichens type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_gedenkzeichentyp_of', to='vocabs.skosconcept', verbose_name='The Gedenkzeichens type')),
                ('related_bomber', models.ManyToManyField(blank=True, help_text='Persons related to this Gedenkzeichen relation', related_name='gd_has_related_bombers', to='entities.bomber', verbose_name='Related bomber')),
                ('related_person', models.ManyToManyField(blank=True, help_text='Persons related to this Gedenkzeichen relation', related_name='gd_has_related_persons', to='entities.person', verbose_name='Related person')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Description', null=True, verbose_name='Description')),
                ('donater_name', models.CharField(blank=True, help_text='Name of the person who provided the material', max_length=250, verbose_name='Beiträger')),
                ('public', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Should this entry (and all related entries) be public', verbose_name='Public')),
                ('legacy_id', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_checked_by', models.ForeignKey(blank=True, help_text='Who checked the entered data.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_checked_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Checked by')),
                ('related_bombers', models.ManyToManyField(blank=True, help_text='Bombers related to this online resource', max_length=250, related_name='usercontribution_bomber', to='entities.bomber', verbose_name='Related bombers')),
                ('related_persons', models.ManyToManyField(blank=True, help_text='Persons related to this online resource', max_length=250, related_name='usercontribution_person', to='entities.person', verbose_name='Related persons')),
                ('related_warcrimecases', models.ManyToManyField(blank=True, help_text='Warcrimecases related to this online resource', max_length=250, related_name='usercontribution_warcrimecase', to='entities.warcrimecase', verbose_name='Related warcrimecases')),
            ],
        ),
    ]
