from django.urls import path
from . import dal_views
from .models import AlternativeName, Place, Institution, Bomber, Person, WarCrimeCase

from vocabs.models import SkosConcept

app_name = "vocabs"

urlpatterns = [
    path(
        "altname-autocomplete/",
        dal_views.AlternativeNameAC.as_view(
            model=AlternativeName,
        ),
        name="altname-autocomplete",
    ),
    path(
        "place-autocomplete/",
        dal_views.PlaceAC.as_view(
            model=Place,
        ),
        name="place-autocomplete",
    ),
    path(
        "crash-place-autocomplete/",
        dal_views.CrashPlaceAC.as_view(
            model=Place,
        ),
        name="crash-place-autocomplete",
    ),
    path(
        "search-place-autocomplete/",
        dal_views.PlaceAC.as_view(),
        name="search-place-autocomplete",
    ),
    path(
        "search-region-autocomplete/",
        dal_views.Region.as_view(),
        name="search-region-autocomplete",
    ),
    path(
        "person-autocomplete/",
        dal_views.PersonAC.as_view(
            model=Place,
        ),
        name="person-autocomplete",
    ),
    path(
        "institution-autocomplete/",
        dal_views.InstitutionAC.as_view(
            model=Institution,
        ),
        name="institution-autocomplete",
    ),
    path(
        "bomberplanetype-autocomplete/",
        dal_views.BomberPlaneTypeAC.as_view(model=SkosConcept),
        name="bomberplanetype-autocomplete",
    ),
    path(
        "bombersquadron-autocomplete/",
        dal_views.BomberSquadronAC.as_view(
            model=Institution,
        ),
        name="bombersquadron-autocomplete",
    ),
    path(
        "bomberreasonofcrash-autocomplete/",
        dal_views.BomberReasonOfCrashAC.as_view(model=SkosConcept),
        name="bomberreasonofcrash-autocomplete",
    ),
    path(
        "personpartofbomber-autocomplete/",
        dal_views.PersonPartOfBomberAC.as_view(model=Bomber),
        name="personpartofbomber-autocomplete",
    ),
    path(
        "personrank-autocomplete/",
        dal_views.PersonRankAC.as_view(model=SkosConcept),
        name="personrank-autocomplete",
    ),
    path(
        "persondestinystated-autocomplete/",
        dal_views.PersonDestinyStatedAC.as_view(model=SkosConcept),
        name="persondestinystated-autocomplete",
    ),
    path(
        "persondestinychecked-autocomplete/",
        dal_views.PersonDestinyCheckedAC.as_view(model=SkosConcept),
        name="persondestinychecked-autocomplete",
    ),
    path(
        "personmia-autocomplete/",
        dal_views.PersonMIAAC.as_view(model=SkosConcept),
        name="personmia-autocomplete",
    ),
    path(
        "onlineressourcerelatedpersons-autocomplete/",
        dal_views.OnlineRessourceRelatedPersonsAC.as_view(
            model=Person,
        ),
        name="onlineressourcerelatedpersons-autocomplete",
    ),
    path(
        "onlineressourcerelatedbombers-autocomplete/",
        dal_views.OnlineRessourceRelatedBombersAC.as_view(
            model=Bomber,
        ),
        name="onlineressourcerelatedbombers-autocomplete",
    ),
    path(
        "onlineressourcerelatedwarcrimecases-autocomplete/",
        dal_views.OnlineRessourceRelatedWarCrimeCasesAC.as_view(
            model=WarCrimeCase,
        ),
        name="onlineressourcerelatedwarcrimecases-autocomplete",
    ),
    path(
        "personwarcrimecaserelatedpersons-autocomplete/",
        dal_views.PersonWarCrimeCaseRelatedPersonsAC.as_view(
            model=Person,
        ),
        name="personwarcrimecaserelatedpersons-autocomplete",
    ),
    path(
        "personwarcrimecaserelatedcases-autocomplete/",
        dal_views.PersonWarCrimeCaseRelatedCasesAC.as_view(
            model=WarCrimeCase,
        ),
        name="personwarcrimecaserelatedcases-autocomplete",
    ),
    path(
        "personwarcrimecaserelationtype-autocomplete/",
        dal_views.PersonWarCrimeCaseRelationTypeAC.as_view(model=SkosConcept),
        name="personwarcrimecaserelationtype-autocomplete",
    ),
    path(
        "warcrimecaserelatedpersons-autocomplete/",
        dal_views.WarCrimeCaseRelatedPersonsAC.as_view(
            model=Person,
        ),
        name="warcrimecaserelatedpersons-autocomplete",
    ),
    path(
        "warcrimecaserelatedcases-autocomplete/",
        dal_views.WarCrimeCaseRelatedCasesAC.as_view(
            model=WarCrimeCase,
        ),
        name="warcrimecaserelatedcases-autocomplete",
    ),
    path(
        "warcrimecaserelatedplaces-autocomplete/",
        dal_views.WarCrimeCaseRelatedPlacesAC.as_view(
            model=Place,
        ),
        name="warcrimecaserelatedplaces-autocomplete",
    ),
    path(
        "warcrimecasecrimetype-autocomplete/",
        dal_views.WarCrimeCaseCrimeTypeAC.as_view(model=SkosConcept),
        name="warcrimecasecrimetype-autocomplete",
    ),
    path(
        "airstriketarget-autocomplete/",
        dal_views.AirstrikeTargetAC.as_view(model=Place),
        name="airstriketarget-autocomplete",
    ),
    path(
        "airstrikeplanetype-autocomplete/",
        dal_views.AirstrikePlaneTypeAC.as_view(model=SkosConcept),
        name="airstrikeplanetype-autocomplete",
    ),
    path(
        "airstrikeairforce-autocomplete/",
        dal_views.AirstrikeAirforceAC.as_view(
            model=Institution,
        ),
        name="airstrikeairforce-autocomplete",
    ),
    path(
        r"specific-place-ac/<str:lookup>",
        dal_views.PlaceConstraintAC.as_view(model=Place),
        name="specific-place-ac",
    ),
    path(
        r"specific-person-ac/<str:lookup>",
        dal_views.PersonConstraintAC.as_view(model=Place),
        name="specific-person-ac",
    ),
]
