# Generated by Django 5.2.1 on 2025-05-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_status', models.CharField(blank=True, choices=[('legacy-data', 'legacy-data'), ('work-in-progress', 'work-in-progress'), ('checked', 'checked')], default='legacy-data', max_length=300)),
            ],
            options={
                'ordering': ['legacy_id'],
            },
        ),
    ]
