# Generated by Django 5.2.1 on 2025-05-13 06:45

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        ('idprovider', '0001_initial'),
        ('vocabs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrisonStation',
            fields=[
                ('idprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='idprovider.idprovider')),
                ('name', models.CharField(help_text='The designation of the prison station', max_length=200, verbose_name='Gefangenschaft')),
                ('station_id', models.CharField(blank=True, help_text='The ID for the prison station', max_length=50, verbose_name='Kennzeichen')),
                ('start_date', models.DateField(blank=True, help_text='The founding date of the prison station', null=True, verbose_name='Gründungsdatum')),
                ('start_date_acc', models.CharField(choices=[('year', 'year'), ('month', 'month'), ('day', 'day')], default='day', help_text='Accuracy of start date field', max_length=50, verbose_name='Accuracy of start date field')),
                ('end_date', models.DateField(blank=True, help_text='Date of dissolution of the prison station', null=True, verbose_name='Auflösungsdatum')),
                ('end_date_acc', models.CharField(choices=[('year', 'year'), ('month', 'month'), ('day', 'day')], default='day', help_text='Accuracy of end date field', max_length=50, verbose_name='Accuracy of end date field')),
                ('description_long', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='A description of the prison station', null=True, verbose_name='Abstract')),
                ('alt_name', models.ManyToManyField(blank=True, help_text='A further name for the prison station', max_length=200, to='entities.alternativename', verbose_name='alternative Bezeichnung des Gefangenenlagers')),
                ('located_in_place', models.ForeignKey(blank=True, help_text='The place where the prison camp is located', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_located', to='entities.place', verbose_name='Ort der Gefangenschaft')),
                ('part_of', models.ForeignKey(blank=True, help_text='The camp that this prison station is part of', null=True, on_delete=django.db.models.deletion.SET_NULL, to='detentions.prisonstation', verbose_name='übergeordnetes Lager')),
                ('station_type', models.ForeignKey(blank=True, help_text='The type of prison station', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_prisonstation_type', to='vocabs.skosconcept', verbose_name='Prison Station Type')),
            ],
            bases=('idprovider.idprovider',),
        ),
        migrations.CreateModel(
            name='PersonPrison',
            fields=[
                ('idprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='idprovider.idprovider')),
                ('start_date', models.DateField(blank=True, help_text='The start date of this PersonPrison relation', null=True, verbose_name='Start of relation')),
                ('start_date_acc', models.CharField(choices=[('year', 'year'), ('month', 'month'), ('day', 'day')], default='day', help_text='Accuracy of start date field', max_length=50, verbose_name='Accuracy of start date field')),
                ('end_date', models.DateField(blank=True, help_text='The end date of this PersonPrison relation', null=True, verbose_name='End of relation')),
                ('end_date_acc', models.CharField(choices=[('year', 'year'), ('month', 'month'), ('day', 'day')], default='day', help_text='Accuracy of end date field', max_length=50, verbose_name='Accuracy of end date field')),
                ('comment', models.TextField(blank=True, help_text='A comment', verbose_name='Comment')),
                ('related_location', models.ForeignKey(blank=True, help_text='Place where some interaction happend', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_to_personprison', to='entities.place', verbose_name='Related Location')),
                ('related_person', models.ForeignKey(blank=True, help_text='Persons related to this PersonPrison relation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_related_persons', to='entities.person', verbose_name='Related person')),
                ('relation_type', models.ForeignKey(blank=True, help_text='The type of the PersonPrison relation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_prisonstation_relation', to='vocabs.skosconcept', verbose_name='Type of relation')),
                ('related_prisonstation', models.ForeignKey(blank=True, help_text='Prison stations related to this PersonPrison relation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_to_prisonstation', to='detentions.prisonstation', verbose_name='Related prison station')),
            ],
            bases=('idprovider.idprovider',),
        ),
    ]
