# Generated by Django 5.2.1 on 2025-05-13 06:45

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idprovider', '0001_initial'),
        ('vocabs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativeName',
            fields=[
                ('idprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='idprovider.idprovider')),
                ('name', models.CharField(blank=True, help_text='An alternative name for a place', max_length=250)),
            ],
            bases=('idprovider.idprovider',),
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('idprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='idprovider.idprovider')),
                ('written_name', models.CharField(blank=True, help_text='The name of the institution', max_length=300, verbose_name='Written name')),
                ('authority_url', models.CharField(blank=True, max_length=300)),
                ('abbreviation', models.CharField(blank=True, help_text='The abbreviation of the institution', max_length=300)),
                ('comment', models.TextField(blank=True)),
                ('alt_names', models.ManyToManyField(blank=True, help_text='Alternative names of the institution', max_length=250, related_name='altname_of_inst', to='entities.alternativename', verbose_name='Alternative Name')),
                ('inst_type', models.ForeignKey(blank=True, help_text="The institution's type", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_inst_type_of', to='vocabs.skosconcept', verbose_name="The institution's type")),
                ('parent_institution', models.ForeignKey(blank=True, help_text='The institution the institution is part of', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_institutions', to='entities.institution')),
            ],
            bases=('idprovider.idprovider',),
        ),
        migrations.CreateModel(
            name='Bomber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_name', models.CharField(blank=True, help_text='The name of the crew aboard this aircraft, named after the pilot', max_length=250, verbose_name='Crewname (Pilot)')),
                ('macr_nr', models.CharField(blank=True, help_text='The Missing Air Crew Reports No.', max_length=50, verbose_name='MACR-Nr')),
                ('plane_id', models.CharField(blank=True, help_text='The plane ID', max_length=50, verbose_name='Flugzeugnr.')),
                ('name', models.CharField(blank=True, help_text='The name of the plane', max_length=250, verbose_name='Flugzeugname')),
                ('date_of_crash', models.DateField(blank=True, help_text="The date of the bomber's crash", null=True, verbose_name='Datum Absturz')),
                ('crash_lat', models.DecimalField(blank=True, decimal_places=12, help_text='The latitude of the exact crashplace. Must not made public!', max_digits=20, null=True, verbose_name='Latitude crash site')),
                ('crash_lng', models.DecimalField(blank=True, decimal_places=12, help_text='The longitude of the exact crashplace. Must not made public!', max_digits=20, null=True, verbose_name='Longitude crash site')),
                ('comment', models.TextField(blank=True, help_text='Space for a comment', verbose_name='Kommentar')),
                ('sicht_koord', models.CharField(blank=True, help_text='Coordinates of the site the bomber was last seen at', max_length=250, verbose_name='Sichtung-Koord')),
                ('sicht_ort', models.CharField(blank=True, help_text='The city or village the bomber was last seen at', max_length=250, verbose_name='Sichtung-Ort')),
                ('sicht_land', models.CharField(blank=True, help_text='The country or county the bomber was last seen at', max_length=250, verbose_name='Sichtung-Land')),
                ('uhrzeit', models.CharField(blank=True, help_text='Time of the day', max_length=250, verbose_name='Uhrzeit')),
                ('uhrzeit_absturz', models.CharField(blank=True, help_text='Time of the crash', max_length=250, verbose_name='Uhrzeit Absturz')),
                ('anmerkung', models.TextField(blank=True, help_text='A comment', verbose_name='Anmerkung (Spalte Y)')),
                ('plane_type', models.ForeignKey(blank=True, help_text='The type of the plane', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_plane_type', to='vocabs.skosconcept', verbose_name='Flugzeugtyp')),
                ('reason_of_crash', models.ForeignKey(blank=True, help_text="The reason for the bomber's crash", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_crash_reason', to='vocabs.skosconcept', verbose_name='Absturzursache')),
                ('squadron', models.ForeignKey(blank=True, help_text='The squadron the bomber belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_bomber', to='entities.institution', verbose_name='Staffel')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OnlineRessource',
            fields=[
                ('idprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='idprovider.idprovider')),
                ('www_url', models.URLField(blank=True, help_text='The URL of the online resource', null=True, verbose_name='URL of online resource')),
                ('description_short', models.CharField(blank=True, help_text='A short description of the online resource', max_length=250, verbose_name='Short description of online resource')),
                ('description_long', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='A long description of the online resource, its abstract', null=True, verbose_name='Abstract')),
                ('related_bombers', models.ManyToManyField(blank=True, help_text='Bombers related to this online resource', max_length=250, related_name='URLbomber', to='entities.bomber', verbose_name='Related bombers')),
            ],
            bases=('idprovider.idprovider',),
        ),
        migrations.AddField(
            model_name='institution',
            name='related_urls',
            field=models.ManyToManyField(blank=True, help_text='URLs related to this institution', max_length=250, related_name='for_institution', to='entities.onlineressource', verbose_name='url'),
        ),
        migrations.AddField(
            model_name='bomber',
            name='related_urls',
            field=models.ManyToManyField(blank=True, help_text='URLs related to this bomber', max_length=250, related_name='for_bomber', to='entities.onlineressource', verbose_name='Related url'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('idprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='idprovider.idprovider')),
                ('dog_tag', models.CharField(blank=True, help_text='The number identifying the person', max_length=300, verbose_name='Kennnummer')),
                ('written_name', models.CharField(blank=True, help_text="The person's full name", max_length=300, verbose_name='Name Kontrolle')),
                ('forename', models.CharField(blank=True, help_text="The person's first name", max_length=300, verbose_name='Vorname')),
                ('name', models.CharField(blank=True, help_text="The person's second name", max_length=300, verbose_name='Familienname')),
                ('middle_name', models.CharField(blank=True, help_text="The person's middle name", max_length=300, verbose_name='Mittelname')),
                ('date_of_birth', models.DateField(blank=True, help_text="The person's date of birth in format YYYY-MM-DD", null=True, verbose_name='Geburtsdatum')),
                ('authority_url', models.CharField(blank=True, max_length=300)),
                ('comment', models.TextField(blank=True, help_text='A comment', verbose_name='Comment')),
                ('detail', models.TextField(blank=True, help_text='Further details concerning the person', verbose_name='Detail')),
                ('me_record', models.CharField(blank=True, help_text='German record about crashed airplane', max_length=250, verbose_name='Maschine Englisch')),
                ('alt_names', models.ManyToManyField(blank=True, help_text='Alternative names for the person', max_length=250, related_name='altname_of_persons', to='entities.alternativename', verbose_name='Alternative name')),
                ('belongs_to_institution', models.ForeignKey(blank=True, help_text='The institution the person belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_member', to='entities.institution', verbose_name='Part of institution')),
                ('destiny_checked', models.ForeignKey(blank=True, help_text="The person's checked destiny", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_dest_checked', to='vocabs.skosconcept', verbose_name='Schicksal')),
                ('destiny_stated', models.ForeignKey(blank=True, help_text="The person's stated destiny according to MACR", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_dest_stated', to='vocabs.skosconcept', verbose_name='Eintrag MACR')),
                ('function_in_plane', models.ForeignKey(blank=True, help_text="The person's function inside the bomber", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_crew_function', to='vocabs.skosconcept', verbose_name='Funktion')),
                ('mia', models.ForeignKey(blank=True, help_text="The person's MIA status", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_mia', to='vocabs.skosconcept', verbose_name='Schicksal genau')),
                ('nation', models.ForeignKey(blank=True, help_text="The person's nationality", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_nationality', to='vocabs.skosconcept', verbose_name='Nationalität')),
                ('part_of_bomber', models.ForeignKey(blank=True, help_text='The bomber the person was part of', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_crew', to='entities.bomber', verbose_name='Part of bomber')),
                ('rank', models.ForeignKey(blank=True, help_text="The person's rank", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_rank', to='vocabs.skosconcept', verbose_name='Dienstgrad')),
                ('related_urls', models.ManyToManyField(blank=True, help_text='URLs related to this person', max_length=250, related_name='for_person', to='entities.onlineressource', verbose_name='Related URLs')),
            ],
            bases=('idprovider.idprovider',),
        ),
        migrations.AddField(
            model_name='onlineressource',
            name='related_persons',
            field=models.ManyToManyField(blank=True, help_text='Persons related to this online resource', max_length=250, related_name='URLperson', to='entities.person', verbose_name='Related persons'),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('idprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='idprovider.idprovider')),
                ('name', models.CharField(blank=True, help_text='The name of the place', max_length=250)),
                ('geonames_id', models.CharField(blank=True, help_text='GND-ID for the place', max_length=50)),
                ('lat', models.DecimalField(blank=True, decimal_places=12, help_text='The latitude of the place', max_digits=20, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=12, help_text='The longitude of the place', max_digits=20, null=True)),
                ('place_type', models.CharField(blank=True, choices=[('city', 'city'), ('country', 'country'), ('region', 'region')], help_text='The type of the place', max_length=50, null=True)),
                ('alt_names', models.ManyToManyField(blank=True, help_text='Alternative names for the place', max_length=250, related_name='altname_of_place', to='entities.alternativename')),
                ('part_of', models.ForeignKey(blank=True, help_text='A place (country) this place is part of', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_child', to='entities.place')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=('idprovider.idprovider',),
        ),
        migrations.AddField(
            model_name='person',
            name='place_of_birth',
            field=models.ForeignKey(blank=True, help_text="The person's birthplace", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_birthplace', to='entities.place', verbose_name='Geburtsort'),
        ),
        migrations.AddField(
            model_name='institution',
            name='location',
            field=models.ForeignKey(blank=True, help_text='The location of the institution', null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.place'),
        ),
        migrations.AddField(
            model_name='bomber',
            name='crash_place',
            field=models.ForeignKey(blank=True, help_text='The place where the bomber crashed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_crashplace', to='entities.place', verbose_name='Absturzort'),
        ),
        migrations.AddField(
            model_name='bomber',
            name='target_place',
            field=models.ForeignKey(blank=True, help_text='The place the bomber targeted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_target_place', to='entities.place', verbose_name='Zielort'),
        ),
        migrations.CreateModel(
            name='Airstrike',
            fields=[
                ('idprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='idprovider.idprovider')),
                ('date', models.DateField(blank=True, help_text='The day the airstrike took place', null=True, verbose_name='Date')),
                ('number_of_planes', models.IntegerField(blank=True, help_text='Estimated number of        planes involved in total', null=True, verbose_name='Number of Planes')),
                ('plane_type', models.ForeignKey(blank=True, help_text='The type of the plane', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_plane_type_2', to='vocabs.skosconcept', verbose_name='Attack type')),
                ('airforce', models.ForeignKey(blank=True, help_text='Name of the Airforce involved in the attack', max_length=250, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_airstrike', to='entities.institution', verbose_name='Airforce')),
                ('target', models.ForeignKey(blank=True, help_text='Place targeted by the airstrike', max_length=250, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_target', to='entities.place', verbose_name='Target place of the airstrike')),
            ],
            options={
                'ordering': ['date'],
            },
            bases=('idprovider.idprovider',),
        ),
        migrations.CreateModel(
            name='WarCrimeCase',
            fields=[
                ('idprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='idprovider.idprovider')),
                ('signatur', models.CharField(blank=True, help_text='The formal number of the War Crime Case', max_length=300, verbose_name='Archivsignatur')),
                ('abstract', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='The abstract of the War Crime Case', null=True, verbose_name='Abstract')),
                ('start_date', models.DateField(blank=True, help_text='The day the War Crime Case started', null=True, verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, help_text='The day the War Crime Case ended', null=True, verbose_name='End date')),
                ('date_accuracy_start', models.CharField(blank=True, choices=[('Y', 'Year'), ('YM', 'Month'), ('DMY', 'Day')], default='Y', help_text='An information stating whether the given start date is accurate', max_length=3, null=True, verbose_name='Date accuracy start date')),
                ('date_accuracy_end', models.CharField(blank=True, choices=[('Y', 'Year'), ('YM', 'Month'), ('DMY', 'Day')], default='Y', help_text='An information stating whether the given end date is accurate', max_length=3, null=True, verbose_name='Date accuracy end date')),
                ('tried', models.CharField(blank=True, choices=[('tried', 'tried'), ('not tried', 'not tried')], help_text='An information stating whether this War Crime Case was tried or not', max_length=250, null=True)),
                ('related_cases', models.ManyToManyField(blank=True, help_text='Other cases related to this War Crime Case', max_length=250, related_name='has_related_cases', to='entities.warcrimecase', verbose_name='Related cases')),
                ('related_persons', models.ManyToManyField(blank=True, help_text='The persons related to this War Crime Case', max_length=250, related_name='mentioned_in_abstract', to='entities.person', verbose_name='Persons mentioned in abstract')),
                ('related_places', models.ManyToManyField(blank=True, help_text='Places related to this War Crime Case', max_length=250, related_name='wcc_mentiones_places', to='entities.place', verbose_name='Places mentioned in abstract')),
                ('related_urls', models.ManyToManyField(blank=True, help_text='URLs related to this War Crime Case', max_length=250, related_name='for_warcrimecase', to='entities.onlineressource', verbose_name='Related URLs')),
                ('type_of_crime', models.ForeignKey(blank=True, help_text='The type of crime committed in this War Crime Case', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crime_type_of', to='vocabs.skosconcept', verbose_name='Type of crime')),
            ],
            bases=('idprovider.idprovider',),
        ),
        migrations.CreateModel(
            name='PersonWarCrimeCase',
            fields=[
                ('idprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='idprovider.idprovider')),
                ('start_date', models.DateField(blank=True, help_text='The start date of this PersonWarCrimeCase relation', null=True, verbose_name='Start date')),
                ('start_date_acc', models.CharField(choices=[('year', 'year'), ('month', 'month'), ('day', 'day')], default='day', help_text='Accuracy of start date field', max_length=50, verbose_name='Accuracy of start date field')),
                ('end_date', models.DateField(blank=True, help_text='The end date of this PersonWarCrimeCase relation', null=True, verbose_name='End date')),
                ('end_date_acc', models.CharField(choices=[('year', 'year'), ('month', 'month'), ('day', 'day')], default='day', help_text='Accuracy of end date field', max_length=50, verbose_name='Accuracy of end date field')),
                ('comment', models.TextField(blank=True, help_text='A comment', verbose_name='Comment')),
                ('related_person', models.ForeignKey(blank=True, help_text='Person related to this PersonWarCrimeCase relation', max_length=250, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_related_warcase', to='entities.person', verbose_name='Persons mentioned in abstract')),
                ('relation_by_crime', models.ForeignKey(blank=True, help_text='The type of this PersonWarCrimeCase relation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relation_by_crime', to='vocabs.skosconcept', verbose_name='Art Verbrechen')),
                ('relation_type', models.ForeignKey(blank=True, help_text='The type of this PersonWarCrimeCase relation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relation_type_of', to='vocabs.skosconcept', verbose_name='Type of relation')),
                ('related_case', models.ForeignKey(blank=True, help_text='Case related to this PersonWarCrimeCase relation', max_length=250, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_to_person', to='entities.warcrimecase', verbose_name='Related case')),
            ],
            bases=('idprovider.idprovider',),
        ),
        migrations.AddField(
            model_name='onlineressource',
            name='related_warcrimecases',
            field=models.ManyToManyField(blank=True, help_text='Warcrimecases related to this online resource', max_length=250, related_name='URLwarcrimecase', to='entities.warcrimecase', verbose_name='Related warcrimecases'),
        ),
    ]
